seyon_teamspeak3_viewer:
    user: xxx
    pass: xxx
    host: xxx
    query: 10011
    voice: 8987
    max_age: 120
    shared_max_age: 120
    template: "SeyonTeamspeak3ViewerBundle::layout.html.twig"